// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEOpeswCNBNm18NC2yArxd2rg6EshDuzQ',
    appId: '1:126330800876:web:0249a3ffb6582b967173c9',
    messagingSenderId: '126330800876',
    projectId: 'concise-ion-368606',
    authDomain: 'concise-ion-368606.firebaseapp.com',
    storageBucket: 'concise-ion-368606.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2DXT8EyYOfpUgz4nUgxuEJbQZUKEkSRI',
    appId: '1:126330800876:android:9c3017073319a34a7173c9',
    messagingSenderId: '126330800876',
    projectId: 'concise-ion-368606',
    storageBucket: 'concise-ion-368606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7rJxEcSrMrrp0bjUKPLoIyZmosNdurUI',
    appId: '1:126330800876:ios:47c00aa7bdb83e297173c9',
    messagingSenderId: '126330800876',
    projectId: 'concise-ion-368606',
    storageBucket: 'concise-ion-368606.appspot.com',
    iosClientId:
        '126330800876-0kcvkpj4gdckugiu7jdi21jk50u696db.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7rJxEcSrMrrp0bjUKPLoIyZmosNdurUI',
    appId: '1:126330800876:ios:2d19623f0a9e8cb37173c9',
    messagingSenderId: '126330800876',
    projectId: 'concise-ion-368606',
    storageBucket: 'concise-ion-368606.appspot.com',
    iosClientId:
        '126330800876-56cs4h0lso48cd2mtl17lfgvjguh24th.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );

// ...
}
